id: PF48C8681
initial_creation_type: input
source_metadata:
  Title: Ḍākinījālasaṃvararahasyam
  Editor: Samdong Rinpoche & Vajravallabhi Dwivedi
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1990'
  Ḍākinījālasaṃvararahasyam:
    Text Version: Romanized
    Input Personnel: Rashmi Shakya
    Input Date: '2015'
    Proof Reader: Rashmi Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:18:30.182051'
last_modified_at: '2022-03-08T16:18:30.182060'
